Bookers_app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  #root "book#new"
  get '/' => 'home#top' ,as: 'root'
  get 'home/about' => 'home#about' ,as: 'home_about'
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update]
  resources :users, only: [:show, :edit,:update,:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Bookers_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers_app/app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user
   validates :title, presence: true
   validates :body, presence: true
   validates :body,    length: { maximum: 200 }
end

Bookers_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true
  validates :name,    length: { maximum: 20,minimum: 2 }
  validates :introduction, length: {maximum: 50 }

end

Bookers_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!,except: [:top,:about]
   before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
     user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
    
  end
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

Bookers_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
    def new
      @book = Book.new

    end
    def create

      @book = Book.new(params_book)
      @book.user = current_user
      @books = Book.all
      if @book.save
        flash[:notice] = "You have created book successfully"
        redirect_to book_path(@book.id)

      else
        render :index
      end
    end

    def show

      @book1 = Book.find(params[:id])

      @user = @book1.user
      @book = Book.new


    end
    def index
      @books = Book.all

      @book = Book.new
      

    end
    def edit
      @book = Book.find(params[:id])

      if @book.user != current_user
        redirect_to books_path
      end
    end
    def update
      @book = Book.find(params[:id])
      @books = Book.all
      @book.update(params_book)
      if @book.save
        flash[:notice] = "You have updated book successfully"
        redirect_to book_path(@book.id)
      else
        render :index
      end
      if @book.user != current_user
        redirect_to :index
      end
    end
    def destroy
      book = Book.find(params[:id])
      book.destroy
      redirect_to book_index_path
    end
  private

  def params_book
    params.require(:book).permit(:title, :body)

  end
end

Bookers_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top

  end
  def about
  end
end

Bookers_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show

    @user = User.find(params[:id])
    @book1 =@user.books
    @book = Book.new
    @user.profile_image = "default_icon.jpg"

  end

  def edit

    @user = User.find(params[:id])
    @users = User.all
    if @user!= current_user
      redirect_to current_user
    end
  end
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = "You have updated user successfully"
      redirect_to user_path(@user.id)

    else
      render :edit

    end
    if @user!= current_user
      redirect_to users_path
    end
  end
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    
    @user.profile_image = "default_icon.jpg"
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction,:profile_image)
  end

end

Bookers_app/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers_app/app/helpers/book_helper.rb
module BookHelper
end

Bookers_app/app/helpers/home_helper.rb
module HomeHelper
end

Bookers_app/app/helpers/user_helper.rb
module UserHelper
end

Bookers_app/app/views/books/_list.html.erb
  <h1 class="">User info</h1>

<%= attachment_image_tag user, :profile_image, format:'jpeg',class: " profile-img", fallback:"snow.jpg",size: "90x90" %></br>

  <p>name:<%=user.name%></p>
  <p>introduction:<%=user.introduction%></p>
    <% if user.id == current_user.id %>
      <p class="mt-3">
        <%= link_to edit_user_path(user) do%>
          <span class="btn btn-default glyphicon glyphicon-wrench col-xs-9"></span>
        <%end%>
        </p>
    <%end%>


  <p>　　</p>
  <h1>New book </h1>
  <%=form_for(book, url:books_path) do |f|%>

    <h4 class="">title</h4>
    <span><%=f.text_field :title %></span>

    <h4 class="">body</h4>
    <span><%=f.text_area :body%></span>

  <p><%=f.submit 'Create Book' ,class: "btn btn-primary"%></p>
  <%end%>

  <%=flash[:notice]%>
  <% if book.errors.any? %>
    <ul>
          <% book.errors.full_messages.each  do |message| %>
          <li>error</li>
          <li><%= message %></li>

      <%end%>
      </ul>
  <%end%>

Bookers_app/app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%=form_for(@book, url:book_path) do |f|%>
  <h4>title</h4>
  <%= f.text_field:title %>
  <h4>body</h4>
  <%= f.text_area:body %>

  <%= f.submit 'Update Book'%>
<%end%>
<%= link_to "Show", book_path(@book)%>
<span> |</span>
<%= link_to "Back", books_path%>

Bookers_app/app/views/books/index.html.erb
  <!-- <div class="row"> -->
  <div class ="container">
    <div class="row">
    <
      <div class=" col-xs-3">
        <%= render 'books/list', user: current_user , book:@book%>
      </div>
  

    <div class ="pull-left col-xs-9">

        <h1>Books</h1>
      <table>
        <tr>
        <td class="pr-10">Title</td>
        <td>Opinion</td>
        </tr>
      </table>

        <table class="table table-striped">
          <% @books.each do |book| %>
          <tr>
            <td><p>
              <%= link_to user_path(book.user) do %>

                <%= attachment_image_tag book.user, :profile_image, fallback:"snow.jpg",format:'jpeg',size: "30x30"%>


              <%end%>
              </p></td>
            <td><p><%= link_to book.title , book_path(book)%></p></td>
            <td><p><%= book.body%></p></td>
          </tr>

      <%end%>
      </table>

      </div>
      </div>

    <!-- </div> -->

Bookers_app/app/views/books/new.html.erb
<h1>Bookers</h1>


<div class ="edit"></div>
  <h1>User info</h1>
<div class= "content">

<%= render 'list',book:@book%>
</div>

Bookers_app/app/views/books/show.html.erb
<div class="container">
  <div class="row">
  <div class ="col-xs-3">
  <%= render 'books/list', user: @user , book:@book1%>
  </div>
    <h1>Book detail</h1>

      <div class =col-xs-9>
      <table class = "table table-striped">
        <td>
        <%=link_to user_path(@user) do %>
          <p><%=  attachment_image_tag @user, :profile_image,fallback:"snow.jpg",format:'jpeg',size: "90x90"%>

          <p><%= @user.name%></p>
        <%end%>
        </td>


        <td><h3><%=link_to @book1.title ,book_path%></h3></td>





        <td><h3><%=@book1.body%></h3></td>

        <% if @book1.user == current_user %>
    <td><%=link_to "Edit" , edit_book_path(@book1)%></td>
    <td><%=link_to "Destroy" ,book_path(@book1), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
  <%end%>
</table>
</div>
</div>
</div>

Bookers_app/app/views/home/about.html.erb
<h1>Welcome to Bookers!!</h1>

Bookers_app/app/views/home/top.html.erb
<body>
  <%=flash[:notice]%>
  <h1>Welcome　to　Bookers</h1>
  <p>In Bookers,</p>
  <p>you can share and exchange your opinions , inpressions , and emotions</p>
  <p>about various books!</p>
  <p><%=link_to "Log in", new_user_session_path,class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in"%></p>
  <p><%=link_to "Sign Up", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1 sign_up"%></p>
</body>

Bookers_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>BookersApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>


  <body>
<header class="clearfix anavbar  navbar-inverse ">
  <!-- <div class="container">
    <div class="row"> -->

    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
  <ul class="nav navbar-nav navbar-right" >
    <% if user_signed_in? %>
    <li>
      <%= link_to "Home", user_path(current_user.id),class:"glyphicon glyphicon-home home "%>
    </li>
      <li>
        <%= link_to 'Users', users_path ,class:"glyphicon glyphicon-user users"%>
      </li>
      <li>

        <%= link_to 'Books', books_path ,class:"glyphicon glyphicon-book books"%>
      </li>
      <li>
        <%= link_to "logout", destroy_user_session_path, method: :delete ,class:"glyphicon glyphicon-log-out logout"%>
      </li>

    <% else %>

    <li>
      <%= link_to "　Home", root_path ,class:"glyphicon glyphicon-home home m-auto"%>
    </li>
    <li ">
      <%= link_to "　About",home_about_path,class:"glyphicon glyphicon-link about"%>
    </li>
      <li >
        <%= link_to "　Sign up", new_user_registration_path,class:"glyphicon glyphicon-edit sign_up" %>
      </li>
      <li>
        <%= link_to "　login", new_user_session_path,class:"glyphicon glyphicon-log-in sign_in p-2"%>
      </li>
    <% end %>
  </ul>
  </nav>
<!-- </div>
</div> -->
</header>
  </body>
  <!-- <div class="container">
    <div class="row"> -->

    <%= yield %>
    <!-- </div>
  </div> -->


</html>

Bookers_app/app/views/users/edit.html.erb
<%=flash[:notice]%>

<%if @user.errors.any?%>
  <ul>
  <% @user.errors.full_messages.each  do |message| %>
            <li>error</li>
            <li><%= message %></li>

  <%end%>
  </ul>
<%end%>
<h1>User info</h1>
<%= form_for(@user) do |f| %>
    <div class="form-group has-icon">
        <span>Name</span>
        <%= f.text_field :name%>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
    </div>

    <div class="form-group has-icon">
   <div class="user-edit-image">
       <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format:'jpeg'%>
   </div>
   <span class="control-span sr-only" ">ProfileImage</span>
   <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>

</div>
     <div class ="">
       <span>introduction</span>
       <%= f.text_field :introduction%>
     </div>
    <%= f.submit "Update User" %>
<% end %>

Bookers_app/app/views/users/index.html.erb
<div class="container">
    <div class="row">
      <div class ="col-xs-3">
        <%= render 'books/list', user: @user , book:@book%>
        </div>

      <div class ="col-xs-9 pull-left">

      <h1>User</h1>
      <span>image</span>
      <table class="table table-striped">

        <%@users.each do |f| %>
        <tr>
          <p>
            <td><%= attachment_image_tag f, :profile_image, fallback:"snow.jpg",format:'jpeg',size: "30x30"%></td>
            <td><%= f.name%></td>
            <td><%= link_to "Show", user_path(f)%></td>
          </p>
        </tr>
        <%end%>
      </table>
      </div>
</div>
</div>
</div>

Bookers_app/app/views/users/show.html.erb
<div class="container clearfix">
  <div class="row">
    <div class="col-xs-3 ">
      <%= render 'books/list', user: @user , book:@book%>
    </div>
    <div class="col-xs-9 pull-left">
      <h1 class="">Books</h1>
      <div class="text-right">
        <table>
        <tr>
          <th>　　　　　　　　　　　　　　　</th>
          <td>
            <span>　title</span>
          </td>
          <td>
            <span>　　　Opinion</span>
          </td>
        </table>
      </div>
      <table class="table table-striped">
        <%@book1.each do |f| %>
        <div class="m-30">

          <tr>
            <p>
              <%= link_to user_path do%>
              <td><%= attachment_image_tag @user, :profile_image,:fill, 90, 90, class:"col-xs-2",format:'jpeg'%></td>
              <%end%>
              <td><%=link_to f.title , book_path(f)%></td>
              <td><%= f.body%></td>
            </p>
          </tr>
        </div>
        <%end%>
      </table>
    </div>
  </div>
</div>